export const USER_SIGNIN_API='USER_SIGNIN_API';

export const LOGIN='LOGIN';

export const GET_USER_SAGA="GET_USER_SAGA";
export const GET_USER_REDUCER="GET_USER_REDUCER";
export const ASSIGN_USER_PROJECT='ASSIGN_USER_PROJECT';
export const REMOVE_FORM_USER='REMOVE_FORM_USER';
export const GET_USER_BY_PROJECT_ID='GET_USER_BY_PROJECT_ID';
export const GET_USER_BY_PROJECT_ID_REDUCER='GET_USER_BY_PROJECT_ID_REDUCER';


export const USER_REGISTER='USER_REGISTER';

export const GET_ALL_USER='GET_ALL_USER';

export const DELETE_USER_MANAGEMENT='DELETE_USER_MANAGEMENT';
export const EDIT_USER_MANAGEMENT='EDIT_USER_MANAGEMENT';

export const EDIT_USER_MANAGEMENT_REDUCER='EDIT_USER_MANAGEMENT_REDUCER';