export const OPEN_DRAWER='OPEN_DRAWER';
export const CLOSE_DRAWER='CLOSE_DRAWER';
export const OPEN_DRAWER_EDIT='OPEN_DRAWER_EDIT';
export  const SET_SUBMIT_FORM='SET_SUBMIT_FORM';
export const OPEN_DRAWER_CREATE_TASK='OPEN_DRAWER_CREATE_TASK';
export const SET_SUBMIT_CREATE_TASK='SET_SUBMIT_CREATE_TASK';