export const GET_ALL_PROJECT='GET_ALL_PROJECT'

export const SET_PROJECT_REDUCER='SET_PROJECT_REDUCER';
export const EDIT_PROJECT='EDIT_PROJECT';

export const UPDATE_PROJECT='UPDATE_PROJECT';

export const DELETE_PROJECT='DELETE_PROJECT';

export const GET_PROJECT_DETAIL='GET_PROJECT_DETAIL';

export const PUT_PROJECT_DETAIL_REDUCER='PUT_PROJECT_DETAIL_REDUCER';

export const GET_ALL_PROJECT_IN_CREATE_TASK='GET_ALL_PROJECT_IN_CREATE_TASK';

export const GET_ALL_PROJECT_IN_CREATE_TASK_REDUCER='GET_ALL_PROJECT_IN_CREATE_TASK_REDUCER';