export const CREATE_TASK='CREATE_TASK';
export const CREATE_TASK_REDUCER='CREATE_TASK_REDUCER';


export const GET_TASK_DETAIL_MODAL='GET_TASK_DETAIL_MODAL';
export const GET_TASK_DETAIL_MODAL_REDUCER='GET_TASK_DETAIL_MODAL_REDUCER';


export const CHANGE_TASK_DETAIL_REDUCER='CHANGE_TASK_DETAIL_REDUCER';
export const CHANGE_ASSIGNESS ='CHANGE_ASSIGNESS';
export const REMOVE_USER_ASSIGNESS ='REMOVE_USER_ASSIGNESS';
export const HANDLE_CHANGE_POST_API='HANDLE_CHANGE_POST_API';

export const UPDATE_STATUS='UPDATE_STATUS';